### ISSUE TITLE
Javascript Error

### ISSUE THREAD

**Issue by nish-on** [salvatejero/cordova-liferay-plugin#1]
On startup of cordova simulator I get the error 

!JavaScript ERROR: module salvatejero.cordova.liferay.Liferay already defined on line 71 for http://localhost:54937/ripple/cordova/cordova-3.5.0.js

**Comment by salvatejero** [comment]
Can you paste a sample of your code?

**Comment by nish-on** [comment]
I did not code anything. I just started a blank cordova project with your liferay plugin and  i added the three jar files for the mobile sdk to the lib folder.

**Comment by salvatejero** [comment]
ok, then, Can you paste Liferay.js?

**Comment by nish-on** [comment]
cordova.define("salvatejero.cordova.liferay.Liferay", function(require, exports, module) {

var argscheck = require('cordova/argscheck'),
    exec = require('cordova/exec'),
    channel = require('cordova/channel'),
    cordova = require('cordova');
var Liferay = {
    connect: function(successCallback, errorCallback, ipServer, userName, password) {
        exec(successCallback, errorCallback, "Liferay", "connect", [ipServer, userName, password]);
    },

```
execute: function(successCallback, errorCallback, className, method, params) {
    exec(successCallback, errorCallback, "Liferay", "execute", [className, method, params]);
}
```

};

channel.onCordovaReady.subscribe(function() {
    Liferay.connect(null, null, 'http://10.0.2.2:8080', 'test@liferay.com', 'test' );

});

module.exports = Liferay;

});

**Comment by salvatejero** [comment]
Please, remove lines

Channnel.on..... To next }); include

**Comment by nish-on** [comment]
I used a ionic cordova project. didn't code anything. just added the three jar files to /www/lib, installed your plugin and removed the lines you proposed me to remove. Now the console outputs. the error is still there : 
2015-09-22 07:30:20.581:INFO:oejsh.ContextHandler:stopped o.e.j.s.ServletContextHandler{/,null}
2015-09-22 07:30:20.989:INFO:oejs.Server:jetty-8.1.16.v20140903
2015-09-22 07:30:20.992:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:56850
!JavaScript LOG: deviceready has not fired after 5 seconds. 
!JavaScript LOG: Channel not fired: onCordovaReady 
!JavaScript LOG: Channel not fired: onCordovaInfoReady 
!JavaScript ERROR: module salvatejero.cordova.liferay.Liferay already defined on line 71 for http://localhost:56848/ripple/cordova/cordova-3.5.0.js 
!JavaScript LOG: deviceready has not fired after 5 seconds. 
!JavaScript LOG: Channel not fired: onCordovaReady 
!JavaScript LOG: Channel not fired: onCordovaInfoReady

**Comment by Nishi-Fertig-Aus** [comment]
Hi Salva,

I went on and I now run the ionic-cordova app in ios simulaitor. I have button and onclick it requests Json Webservices. My Code is 

function makeJsonCall() {
	console.log('Json Call 1');
	Liferay.connect(null, null, 'http://localhost:8080', 'test@liferay.com', 'test' );
	console.log('Json Call 2');
	Liferay.execute(successCallback, errorCallback, 'com.liferay.portal.model.Country', 'getCountryByA2', ['de']);
	console.log('Json Call 3');
}
function successCallback(){
	console("success");
}
function errorCallback(){
	console("error");
}

But after the Click the log only returns: 

2015-09-29 16:13:27.145 hello12[11529:16455658] DiskCookieStorage changing policy from 2 to 0, cookie file: file:///Users/Nishi/Library/Developer/CoreSimulator/Devices/31F0D632-2957-4E79-A75E-58A65AA35B47/data/Containers/Data/Application/A8A11B74-8A23-438F-8CA5-43D30CEC58D9/Library/Cookies/com.ionicframework.hello12493398.binarycookies
2015-09-29 16:13:27.293 hello12[11529:16455658] Apache Cordova native platform version 3.8.0 is starting.
2015-09-29 16:13:27.295 hello12[11529:16455658] Multi-tasking -> Device: YES, App: YES
2015-09-29 16:13:27.307 hello12[11529:16455658] Unlimited access to network resources
2015-09-29 16:13:27.480 hello12[11529:16455658] [CDVTimer][keyboard] 0.131011ms
2015-09-29 16:13:27.768 hello12[11529:16455658] [CDVTimer][splashscreen] 287.216008ms
2015-09-29 16:13:27.769 hello12[11529:16455658] [CDVTimer][TotalPluginStartup] 289.326966ms
2015-09-29 16:13:28.099 hello12[11529:16455658] Resetting plugins due to page load.
2015-09-29 16:13:29.126 hello12[11529:16455658] Finished load of: file:///Users/Nishi/Library/Developer/CoreSimulator/Devices/31F0D632-2957-4E79-A75E-58A65AA35B47/data/Containers/Bundle/Application/92E94BF1-8945-41DF-B39E-2E959AEA2062/hello12.app/www/index.html#/tab/dash
2015-09-29 16:13:44.691 hello12[11529:16455658] Json Call 1

It gets stuck with Liferay.connect .

Do you have any idea how to solve this issue?

**Comment by nish-on** [comment]
Hi Salva, 

I went on and now I try to run your plugin with ios simulator. Unfortunately I got this error. Can you help how to solve it?

![2015-09-29 05 41 13 pm](https://cloud.githubusercontent.com/assets/14584718/10169474/86d49c5c-66d1-11e5-967c-100d95afcec5.png)

**Comment by salvatejero** [comment]
Hi, You need to add in your plist default-company-id

The define error p, it's possible that Liferay has changed the library, this weekend I will update the project

**Comment by nish-on** [comment]
Hi Salva, the Error is that the Files are not found. I'm new to iOS so I just followed the description in your tutorials and I used 'add files' to add the liferay-ios-sdk and AFNetworking and I added the liferay-corodova-plugin with cordova CLI . I hope you will post the answer this weekend. Otherwise I'm stuck. Thank you very much for your efforts.

**Comment by nish-on** [comment]
Hi Salva, I just exchanged the latest liferay-ios-sdk version with older ones, last the 6.0.13 version and the error, that the files of the import statements are not found, is still there.

**Comment by salvatejero** [comment]
Hi Nishi,

https://github.com/liferay/liferay-mobile-sdk/tree/master/ios/Source/Core
In Liferay mobile sdk github repository exists the file LRSession.h. This file must be in Core Folder. is it possible that you don't include in build?

**Comment by nish-on** [comment]
Hi Salva,
you are right. Thank you. I'm new to iOS, so I didn't know the difference between 'add files'  with the option 'create groups' and 'create folder references'. The Default setting was 'create folder references' . After Changing to 'create groups' the import works. But now the compiler says this. 

![2015-09-30 11 14 05 am](https://cloud.githubusercontent.com/assets/14584718/10189272/9a6b99e8-6765-11e5-8083-8d7f25b40f14.png)

**Comment by salvatejero** [comment]
Ok, this is other problem with SDK version. The last version that I check
the cordova plugin was 6.2 nor 6.2.21.

This weekend, I will try to update de plugin

-- Salva Tejero --

2015-09-30 11:24 GMT+02:00 Nishi-Fertig-Aus notifications@github.com:

**Comment by salvatejero** [comment]
Hi, I've just make a commit. Can you check if all is ok?

-- Salva Tejero --

2015-09-30 12:35 GMT+02:00 Salva Tejero salva.tejero@gmail.com:

**Comment by nish-on** [comment]
Hi Salva,

Thank you for the update. I just created a Cordova Project with CLI. I added iOS to it. I imported the iOS Project file XCode. I created a podfile. I ran CocoaPods. I closed the Project. I opend the  Hello19.xcworkspace file with XCode. I ran the project and there were no errors. After this I installed your plugin with CLI. After cleaning and running I get this error. 
![2015-10-06 11 11 55 am](https://cloud.githubusercontent.com/assets/14584718/10304646/b74ad190-6c1b-11e5-96fc-9f41d25ee308.png)

**Comment by salvatejero** [comment]
This file must be in the Liferay folder. I don't use cocoad. I've
downloaded the file from Liferay-sdk-mobile github

-- Salva Tejero --

2015-10-06 11:17 GMT+02:00 Nishi-Fertig-Aus notifications@github.com:

**Comment by nish-on** [comment]
If I include the mobile SDK and AFNetworking manually, I have got issues with AFNetworking. I deleted the test and example folder in AFNetworking because the throw errors as well. I used the latest version 2.5.3 of AFNetworking, do you use the same one? 
![2015-10-06 12 58 12 pm](https://cloud.githubusercontent.com/assets/14584718/10306890/6029cc68-6c2a-11e5-8a1e-688f7235d01c.png)
![2015-10-06 12 57 56 pm](https://cloud.githubusercontent.com/assets/14584718/10306895/6e0a9dda-6c2a-11e5-920b-69d74cb5d570.png)

**Comment by salvatejero** [comment]
I have tested with  260 KB liferay-ios-sdk-6.2.0.21.zip
https://github.com/liferay/liferay-mobile-sdk/releases/download/ios-6.2.0.21/liferay-ios-sdk-6.2.0.21.zip

-- Salva Tejero --

2015-10-06 13:02 GMT+02:00 Nishi-Fertig-Aus notifications@github.com:

**Comment by nish-on** [comment]
And what about AFNetworking? The Documentation by Bruno Farache says that Liferay-ios-SDK has got dependencies in AFNetworking. Don't you use AFNetworking?

**Comment by salvatejero** [comment]
You must use https://github.com/AFNetworking/AFNetworking/releases/tag/2.5.3

-- Salva Tejero --

2015-10-06 13:55 GMT+02:00 Nishi-Fertig-Aus notifications@github.com:

**Comment by nish-on** [comment]
Hi Salva,

I'm new to Xcode, so I just tried a lot. Finally I know now why i got these errors with AFNetworking. What I did wrong was to include the ios-mobile-sdk and AFNetworking with "add files" function in Xcode. When I go on the project file and add them under General -> Linked Frameworks and Librarys with the '+'. Everything works perfect. But after installing your plugin I see these errors. Even if I include your plugin in the same way as the other two libraries I get the same error for your plugin. Do you have any idea, how to get it working?

![2015-10-07 07 52 20 am](https://cloud.githubusercontent.com/assets/14584718/10330126/843b32b4-6cc9-11e5-9e38-7e1c414b83ee.png)

**Comment by salvatejero** [comment]
Have you linked this frameworks?
<img width="806" alt="captura de pantalla 2015-10-07 a las 16 56 30" src="https://cloud.githubusercontent.com/assets/2272525/10341293/6ec413e2-6d14-11e5-8d9b-e0a346ec4ff5.png">

**Comment by nish-on** [comment]
Now I have added the Security.framework as well as the SystemConfiguration.framework.  Unfortunately this does not solve the issue. I get the same errors as before.

**Comment by salvatejero** [comment]
you must be sure that all AF*.m are included in "Compile Source". I have included 141 files

**Comment by salvatejero** [comment]
And this is my prefix.pch

#ifdef **OBJC**
    #import <Foundation/Foundation.h>
    #import <Security/Security.h>
    #import <UIKit/UIKit.h>
#endif

**Comment by nish-on** [comment]
I have added the .m files. Totally there were about 160 files imported. After removing some files again. I have a total number of 144 files. Before including there were 4 files. So I included 140 files. I couldn't remove GlobalTimelineViewController.m because it is used by your plugin. But it throws an Exception. I have a Hello37-Prefix.pch file in the project. But after changing it to the code you proposed, it threw an exception as well. 

![2015-10-07 06 33 22 pm](https://cloud.githubusercontent.com/assets/14584718/10344322/d1033282-6d22-11e5-86ee-ff2712aca09c.png)

![2015-10-07 06 34 03 pm](https://cloud.githubusercontent.com/assets/14584718/10344331/e256f1e0-6d22-11e5-8ff7-193d29f7c803.png)

**Comment by nish-on** [comment]
Hi Salva,

I was able to get the project running without errors. Your proposition to add the .m files to the 'compile sources' did it. The Errors which I had, were thrown by the test and example subfolders of AFNetworking. I only included the .m source files of AFNetworking Subfolder and UIKit+AFNetworking Subfolder. Right now I couldn't test if I can request Data from Liferay with your plugin. But I will try this soon. Thank you for your help.

**Comment by nish-on** [comment]
Hi Salva, I tried to retrieve Data from localhost:8080. I've checked and the server is running. I have removed the lines you proposed to remove in your third post in this thread, but i get the same javascript error. makeJsonCall is fired onclick. 

This is my code : 

function makeJsonCall() {
    console.log('Hello Nishi');
    Liferay.connect(null, null, 'http://localhost:8080', 'test@liferay.com', 'test' );
    Liferay.execute(successCallback, errorCallback, 'com.liferay.portal.model.Country', 'getCountryByA2', 'af');
}
function successCallback(data){
    console.log("success");
    console.log(data);
}
function errorCallback(){
    console.log("error");
}

This is the error which is showed in Safari's console for the iOS Simulator. 

![2015-10-10 10 28 42 am](https://cloud.githubusercontent.com/assets/14584718/10410188/06c2cfea-6f3a-11e5-88bb-48ea6dd67ae8.png)

**Comment by salvatejero** [comment]
Hi,

My Liferay.js content is:

cordova.define("salvatejero.cordova.liferay.Liferay", function(require,
exports, module) {

```
var argscheck = require('cordova/argscheck'),
    exec = require('cordova/exec'),
    channel = require('cordova/channel'),
    cordova = require('cordova');

var Liferay = {
    connect: function(successCallback, errorCallback, ipServer,
```

userName, password) {
               exec(successCallback, errorCallback, "Liferay", "connect",
[ipServer, userName, password]);
        },

```
    execute: function(successCallback, errorCallback, className,
```

method, params) {
               exec(successCallback, errorCallback, "Liferay", "execute",
[className, method, params]);
               }
        };

```
    channel.onCordovaReady.subscribe(function() {
            Liferay.connect(onSuc, onError, 'http://192.168.0.199:8080',
```

'test@liferay.com', 'test' );

```
    });

module.exports = Liferay;
```

});

and then, in my button i have this method

Liferay.execute(onSuccess2, null,
'com.liferay.portal.model.User','getUserByEmailAddress',[10154, '
test@liferay.com']);

The params(last) are an array[] also if it has only one param.

-- Salva Tejero --

2015-10-10 10:35 GMT+02:00 Nishi-Fertig-Aus notifications@github.com:

**Comment by salvatejero** [comment]
My cordova_plugins.js

cordova.define('cordova/plugin_list', function(require, exports, module) {
module.exports = [
    {
        "file": "plugins/org.apache.cordova.device/www/device.js",
        "id": "org.apache.cordova.device.device",
        "clobbers": [
            "device"
        ]
    },
    {
        "file":
"plugins/org.apache.cordova.network-information/www/network.js",
        "id": "org.apache.cordova.network-information.network",
        "clobbers": [
            "navigator.connection",
            "navigator.network.connection"
        ]
    },
    {
        "file":
"plugins/org.apache.cordova.network-information/www/Connection.js",
        "id": "org.apache.cordova.network-information.Connection",
        "clobbers": [
            "Connection"
        ]
    },
    {
        "file": "plugins/salvatejero.cordova.liferay/www/Liferay.js",
        "id": "salvatejero.cordova.liferay.Liferay",
        "clobbers": [
             "Liferay"
        ]
    }
];
module.exports.metadata =
// TOP OF METADATA
{
    "org.apache.cordova.device": "0.2.13",
    "org.apache.cordova.network-information": "0.2.14",
    "salvatejero.cordova.liferay": "0.1.0"
}
// BOTTOM OF METADATA
});

and config.xml

IOS:

<feature name="Liferay">

```
    <param name="ios-package" value="LiferayPlugin" />

</feature>
```

Android:

<feature name="Liferay">

```
    <param name="android-package" value=
```

"salvatejero.cordova.liferay.LiferayPlugin" />

```
</feature>
```

-- Salva Tejero --

2015-10-10 18:58 GMT+02:00 Salva Tejero salva.tejero@gmail.com:

**Comment by nish-on** [comment]
Hi Salva, im using localhost:8080 or 127.0.0.1:8080. Before I hadn't installed the network.js and the Connection.js. But after installing these the error is the same. In conrdova_plugin.js there is everything similar except the versions . Could you please try out your plugin with a new ionic project from ionicframework.com/getting-started?

after installing ionic with '$npm install -g cordova ionic' you create a new project for ios platform with 
'$ ionic start myApp tabs' in the folder you are in. 

module.exports.metadata = 
// TOP OF METADATA
{
    "com.ionic.keyboard": "1.0.4",
    "cordova-plugin-console": "1.0.1",
    "cordova-plugin-device": "1.0.1",
    "cordova-plugin-splashscreen": "2.1.0",
    "cordova-plugin-whitelist": "1.0.0",
    "salvatejero.cordova.liferay": "0.2.14-dev",
    "cordova-plugin-network-information": "1.0.1"
}

**Comment by nish-on** [comment]
The error has also nothing to do with the ip address localhost, because I just started a bitnami liferay instance on Amazon Webservices and tested it and the Error is still the Javascript Error "Can't find Liferay"

**Comment by condor2k** [comment]
@salvatejero can you please add a simple test project. Your documentation is not sufficient for me.

**Comment by nish-on** [comment]
Hi Salva, here is my project https://s3-eu-west-1.amazonaws.com/miscellaneous-nishi/LiferayIonic2.zip 

In iOS Simulator please click the left button at the bottom with the flask. To see the error please open a safari browser. In the Main menu choose 'Develop' and then 'iOS Simulator' and then index.html. Have a look at the logs in the console, when you click the flask button.

**Comment by salvatejero** [comment]
A Basic Example https://github.com/salvatejero/cordova-liferay-plugin/blob/master/examples/basic-example.zip

The example only contains Android vesion but www folder is shared
Tomorrow I will upload a Ionic Example

**Comment by salvatejero** [comment]
The plugin has been uploaded to last cordova version

**Comment by condor2k** [comment]
Thank you - this example can at least connect to a LR. I then get a "authentication token invalid" error, but that's another story.

**Comment by salvatejero** [comment]
Great!!! By default I use the company  10154.
you must make sure that this company exist. By the other hand, you can
define a preferences to use another company.

JSONObject user = userService.getUserByEmailAddress(preferences.getInteger(
"liferay-company-default", 10154), username);

-- Salva Tejero --

2015-10-15 10:04 GMT+02:00 condor2k notifications@github.com:
