### ISSUE TITLE
Uncaught module salvatejero.cordova.liferay.Liferay already defined

### ISSUE THREAD

**Issue by condor2k** [salvatejero/cordova-liferay-plugin#2]
Can't get it running under android with cordova 5.3.3

```
cordova create lrtest
cd lrtest
cordova platform android add
cordova plugin add https://github.com/salvatejero/cordova-liferay-plugin.git
```

Added lrtest\platforms\android\build-extras.gradle

```
ext.postBuildExtras = {
    android {
        compileOptions {
            sourceCompatibility JavaVersion.VERSION_1_7
            targetCompatibility JavaVersion.VERSION_1_7
        }
    }
}
```

COPIED liferay-android-sdk-6.2.0.21.jar to lrtest\platforms\android\libs
ALSO tried liferay-android-sdk-6.2.0.22.jar

```
cordova build
cordova run
```

Error message:

```
I/chromium( 3267): [INFO:CONSOLE(79)] "Uncaught module salvatejero.cordova.liferay.Liferay already defined", source: file:///android_asset/www/cordova.js (79)
I/chromium( 3267): [INFO:CONSOLE(1183)] "deviceready has not fired after 5 seconds.", source: file:///android_asset/www/cordova.js (1183)
I/chromium( 3267): [INFO:CONSOLE(1176)] "Channel not fired: onCordovaReady", source: file:///android_asset/www/cordova.js (1176)
```

**Comment by salvatejero** [comment]
Ok, tomorrow I will try to commit a ionic example and other basic example

C/c @Nishi-Fertig-Aus

**Comment by salvatejero** [comment]
The Basic Example

https://github.com/salvatejero/cordova-liferay-plugin/blob/master/examples/basic-example.zip

**Comment by salvatejero** [comment]
The plugin has been uploaded to last cordova version

**Comment by salvatejero** [comment]
I commit a new version of basic-example.zip with IOS example

**Comment by nish-on** [comment]
Hi Salva,

Thank you for the basic example. I have modified your code to this 

```
    Liferay.connect(function (data){
        console.log("success "+data);
        Liferay.execute(null, null, 'com.liferay.portal.model.Country', 'getCountryByA2', '[af]');
        var parentElement = document.getElementById('deviceready');
        var connectingElement = parentElement.querySelector('.connecting');
        var connectedElement = parentElement.querySelector('.connected');
        connectingElement.setAttribute('style', 'display:none;');
        connectedElement.setAttribute('style', 'display:block;');
    }, function (data){
        console.log("error "+data);
        var parentElement = document.getElementById('deviceready');
        var connectingElement = parentElement.querySelector('.connecting');
        var errorElement = parentElement.querySelector('.errorConnecting');
        connectingElement.setAttribute('style', 'display:none;');
        errorElement.setAttribute('style', 'display:block;');
    }, 'http://52.18.10.61/liferay', 'user@liferay.com', 'user'  );
},
```

And this is the Exception that is thrown

2015-10-16 18:29:56.389 BasicExample[1601:1066828] Error Domain=com.liferay.mobile.sdk Code=2 "com.liferay.portal.NoSuchUserException" UserInfo={NSLocalizedDescription=com.liferay.portal.NoSuchUserException}
2015-10-16 18:29:56.394 BasicExample[1601:1066828] THREAD WARNING: ['Liferay'] took '1420.035645' ms. Plugin should use a background thread.

Can you help?

**Comment by salvatejero** [comment]
Hi @Nishi-Fertig-Aus 

The call of the method is wrong

Liferay.execute(function (dat){ console.log(dat); }, null, 'com.liferay.portal.model.Country', 'getCountryByA2', ['af']);

By the other hand, I solved two issues one for Android and one for IOS.

Another thing, Plist file in IOS and config.xml in Android, you must change the preference "liferay-company-default" and put your correct companied

Your log error is that Liferay can't find a user with this mail and pass in company

**Comment by nish-on** [comment]
In the BasicExample-info.plist file I changed this in the first lines:

```
<key>default-company-id</key>
<string>20155</string>
<key>liferay-company-default</key>
<string>20155</string>
```

This ist my Code in Index.js

```
   Liferay.connect(function (data){
        Liferay.execute(function(dat){console.log(dat);}, null, 'com.liferay.portal.model.User', 'geUserByEmailAddress', [20155,'user@liferay.com']);
        var parentElement = document.getElementById('deviceready');
        var connectingElement = parentElement.querySelector('.connecting');
        var connectedElement = parentElement.querySelector('.connected');
        connectingElement.setAttribute('style', 'display:none;');
        connectedElement.setAttribute('style', 'display:block;');
        console.log("success "+data);
    }, function (data){
        var parentElement = document.getElementById('deviceready');
        var connectingElement = parentElement.querySelector('.connecting');
        var errorElement = parentElement.querySelector('.errorConnecting');
        connectingElement.setAttribute('style', 'display:none;');
        errorElement.setAttribute('style', 'display:block;');
        console.log("error "+data);
    }, 'http://52.18.10.61/liferay', 'user@liferay.com', 'user'  );
```

And this is the log printing on click.

2015-10-16 21:01:39.331 BasicExample[2930:2273491](null)
2015-10-16 21:01:39.349 BasicExample[2930:2273491] THREAD WARNING: ['Liferay'] took '502.492188' ms. Plugin should use a background thread.

**Comment by salvatejero** [comment]
I think all is ok. Nothing wrong in your code. Is the connectedElement
showed?

El viernes, 16 de octubre de 2015, Nishi-Fertig-Aus <
notifications@github.com> escribió:

> In the BasicExample-info.plist file I changed this in the first lines:
> 
> <key>default-company-id</key>
> <string>20155</string>
> <key>liferay-company-default</key>
> <string>20155</string>
> 
> This ist my Code in Index.js
> 
>    Liferay.connect(function (data){
>         Liferay.execute(function(dat){console.log(dat);}, null, 'com.liferay.portal.model.User', 'geUserByEmailAddress', [20155,'user@liferay.com <javascript:_e(%7B%7D,'cvml','user@liferay.com');>']);
>         var parentElement = document.getElementById('deviceready');
>         var connectingElement = parentElement.querySelector('.connecting');
>         var connectedElement = parentElement.querySelector('.connected');
>         connectingElement.setAttribute('style', 'display:none;');
>         connectedElement.setAttribute('style', 'display:block;');
>         console.log("success "+data);
>     }, function (data){
>         var parentElement = document.getElementById('deviceready');
>         var connectingElement = parentElement.querySelector('.connecting');
>         var errorElement = parentElement.querySelector('.errorConnecting');
>         connectingElement.setAttribute('style', 'display:none;');
>         errorElement.setAttribute('style', 'display:block;');
>         console.log("error "+data);
>     }, 'http://52.18.10.61/liferay', 'user@liferay.com <javascript:_e(%7B%7D,'cvml','user@liferay.com');>', 'user'  );
> 
> And this is the log printing on click.
> 
> 2015-10-16 21:01:39.331 BasicExample2930:2273491 http://null
> 2015-10-16 21:01:39.349 BasicExample[2930:2273491] THREAD WARNING:
> ['Liferay'] took '502.492188' ms. Plugin should use a background thread.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/salvatejero/cordova-liferay-plugin/issues/2#issuecomment-148807803
> .

## 

-- Salva Tejero --

**Comment by nish-on** [comment]
The iOS Screen doesn't change and I only get the two lines above logged to the console. You can try it with the same server ( http://52.18.10.61/liferay ). It's online.

**Comment by salvatejero** [comment]
I have just found the problem, the method's name is getUserByEmailAddress not geUserByEmailAddress, you have forgotten a "t"

**Comment by nish-on** [comment]
Thank you very much for the correction of my code. Now the iOS screen still doesn't change and the iOS console say this

2015-10-17 09:43:28.780 BasicExample[3737:6919872](null)
2015-10-17 09:43:28.806 BasicExample[3737:6919872] THREAD WARNING: ['Liferay'] took '463.636963' ms. Plugin should use a background thread.
2015-10-17 09:43:28.847 BasicExample[3737:6919872] @40@0:8q16@24^@32
2015-10-17 09:43:29.075 BasicExample[3737:6919872](null)
2015-10-17 09:43:29.077 BasicExample[3737:6919872] THREAD WARNING: ['Liferay'] took '270.731934' ms. Plugin should use a background thread.

and the safari console says 

![2015-10-17 09 44 40 am](https://cloud.githubusercontent.com/assets/14584718/10557607/e4e29f52-74b3-11e5-8d78-8e5e477664e1.png)

And there is no data to display on click of this line.

**Comment by salvatejero** [comment]
The safari console is ok. [Object object] os the json result. This method
is ok. You can try to access any attribute of Country object in your
successCallback function

El sábado, 17 de octubre de 2015, Nishi-Fertig-Aus notifications@github.com
escribió:

> Thank you very much for the correction of my code. Now the iOS screen
> still doesn't change and the iOS console say this
> 
> 2015-10-17 09:43:28.780 BasicExample3737:6919872 http://null
> 2015-10-17 09:43:28.806 BasicExample[3737:6919872] THREAD WARNING:
> ['Liferay'] took '463.636963' ms. Plugin should use a background thread.
> 2015-10-17 09:43:28.847 BasicExample[3737:6919872] @40
> https://github.com/40@0:8q16@24^@32 https://github.com/32
> 2015-10-17 09:43:29.075 BasicExample3737:6919872 http://null
> 2015-10-17 09:43:29.077 BasicExample[3737:6919872] THREAD WARNING:
> ['Liferay'] took '270.731934' ms. Plugin should use a background thread.
> 
> and the safari console says
> 
> [image: 2015-10-17 09 44 40 am]
> https://cloud.githubusercontent.com/assets/14584718/10557607/e4e29f52-74b3-11e5-8d78-8e5e477664e1.png
> 
> And there is no data to display on click of this line.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/salvatejero/cordova-liferay-plugin/issues/2#issuecomment-148893541
> .

## 

-- Salva Tejero --

**Comment by salvatejero** [comment]
Sorry, User object

El sábado, 17 de octubre de 2015, Salva Tejero salva.tejero@gmail.com
escribió:

>  The safari console is ok. [Object object] os the json result. This method
> is ok. You can try to access any attribute of Country object in your
> successCallback function
> 
> El sábado, 17 de octubre de 2015, Nishi-Fertig-Aus <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> escribió:
> 
> > Thank you very much for the correction of my code. Now the iOS screen
> > still doesn't change and the iOS console say this
> > 
> > 2015-10-17 09:43:28.780 BasicExample3737:6919872 http://null
> > 2015-10-17 09:43:28.806 BasicExample[3737:6919872] THREAD WARNING:
> > ['Liferay'] took '463.636963' ms. Plugin should use a background thread.
> > 2015-10-17 09:43:28.847 BasicExample[3737:6919872] @40
> > https://github.com/40@0:8q16@24^@32 https://github.com/32
> > 2015-10-17 09:43:29.075 BasicExample3737:6919872 http://null
> > 2015-10-17 09:43:29.077 BasicExample[3737:6919872] THREAD WARNING:
> > ['Liferay'] took '270.731934' ms. Plugin should use a background thread.
> > 
> > and the safari console says
> > 
> > [image: 2015-10-17 09 44 40 am]
> > https://cloud.githubusercontent.com/assets/14584718/10557607/e4e29f52-74b3-11e5-8d78-8e5e477664e1.png
> > 
> > And there is no data to display on click of this line.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/salvatejero/cordova-liferay-plugin/issues/2#issuecomment-148893541
> > .
> 
> ## 
> 
> -- Salva Tejero --

## 

-- Salva Tejero --

**Comment by nish-on** [comment]
Thank you very much Salva. It works !!! That is awesome.

**Comment by salvatejero** [comment]
Great news!!!!! If you find other problem, please opten a new issue
